
const CLEAR_LOGIN = 'CLEAR_LOGIN';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
const LOGIN_SUBMIT_END = 'LOGIN_SUBMIT_END';
const UPDATE_FIELD = 'UPDATE_FIELD';

export {
  CLEAR_LOGIN,
  LOGIN_FAILURE,
  LOGIN_SUBMIT,
  LOGIN_SUCCESS,
  LOGIN_SUBMIT_END,
  UPDATE_FIELD
}