const DO_LOGIN = 'DO_LOGIN';
const HANDLE_LOGIN_FAILURE = 'HANDLE_LOGIN_FAILURE';
const HANDLE_LOGIN_SUCCESS = 'DO_HANDLE_LOGIN_SUCCESS';
const REDIRECT_TO_HOME = 'REDIRECT_TO_HOME';
const UPDATE_SESSION = 'UPDATE_SESSION';
const UPDATE_SESSION_ID = 'UPDATE_SESSION_ID';

export {
  HANDLE_LOGIN_FAILURE,
  HANDLE_LOGIN_SUCCESS,
  DO_LOGIN,
  REDIRECT_TO_HOME,
  UPDATE_SESSION,
  UPDATE_SESSION_ID
}